# Generated by Django 5.0 on 2024-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saves',
            field=models.ManyToManyField(related_name='saved_posts', to='main.post'),
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
