# Generated by Django 5.0 on 2024-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
