# Generated by Django 5.0 on 2024-01-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
