# Generated by Django 5.0 on 2024-01-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_comments_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='main.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
