# Generated by Django 5.0 on 2024-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default='zab', max_length=60),
        ),
    ]
